vim.keymap.set('n', '<Esc>', '<cmd>nohlsearch<CR>')

vim.keymap.set('n', '<C-h>', '<C-w><C-h>', { desc = 'Focus left split' })
vim.keymap.set('n', '<C-l>', '<C-w><C-l>', { desc = 'Focus right split' })
vim.keymap.set('n', '<C-j>', '<C-w><C-j>', { desc = 'Focus bottom split' })
vim.keymap.set('n', '<C-k>', '<C-w><C-k>', { desc = 'Focus top split' })
vim.keymap.set("n", "<C-=>", "<C-w>+", { desc = "Increase split height" })
vim.keymap.set("n", "<C-->", "<C-w>-", { desc = "Decrease split height" })
vim.keymap.set("n", "<C-,>", "<C-w><", { desc = "Decrease split width" })
vim.keymap.set("n", "<C-.>", "<C-w>>", { desc = "Increase split width" })
