format = """
$directory\
$git_branch\
$git_commit\
$git_status\
$line_break\
$character
"""

[character]
success_symbol = "[→](bold green)"
error_symbol = "[→](bold red)"
vimcmd_symbol = "[←](bold green)"

[git_commit]
tag_symbol = " tag "

[git_status]
ahead = "↑"
behind = "↓"
diverged = "↕"
renamed = "r"
deleted = "x"

[directory]
read_only = " ro"

[git_branch]
symbol = ""
