# Neovim
alias vim="nvim"

# C Compiler Helper
# Shorthand for compiling and running C code
c() {
    if [ -z "$1" ]; then
        echo "Usage: c [.c file] < [input]"
        return 1
    fi

    clang "$1" && ./a.out
}
