# Homebrew
eval "$(/opt/homebrew/bin/brew shellenv)"

# Go tools
export PATH="$PATH:$HOME/go/bin"

# Starship.rs
eval "$(starship init zsh)"

# Source local aliases
source ~/.zshrc_local

# Mise
eval "$(/Users/nolinmcfarland/.local/bin/mise activate zsh)" # added by https://mise.run/zsh
